// honim_frontend/src/pages/KitchenPage.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { CheckCircle2, ChefHat, Clock3, RefreshCw, Utensils } from '@lucide/vue'
import { api } from '../api'
import type { Order } from '../types'
import KitchenTicket from '../components/KitchenTicket.vue'

const orders=ref<Order[]>([]), loading=ref(true), busy=ref<number>(), error=ref(''), updated=ref<Date>()
let timer:number|undefined
const queued=computed(()=>orders.value.filter(order=>order.preparation_status==='queued'))
const preparing=computed(()=>orders.value.filter(order=>order.preparation_status==='preparing'))
const ready=computed(()=>orders.value.filter(order=>order.preparation_status==='ready'))

async function load(silent=false){
  if(!silent)loading.value=true
  try{orders.value=await api<Order[]>('kitchen/orders/');updated.value=new Date();error.value=''}
  catch(e){error.value=(e as Error).message}
  finally{loading.value=false}
}
async function advance(order:Order){
  const next=order.preparation_status==='queued'?'preparing':order.preparation_status==='preparing'?'ready':'served'
  busy.value=order.id;error.value=''
  try{await api(`kitchen/orders/${order.id}/status/`,{method:'POST',body:JSON.stringify({status:next})});await load(true)}
  catch(e){error.value=(e as Error).message;await load(true)}
  finally{busy.value=undefined}
}
const actionLabel=(status:string)=>status==='queued'?'Tayyorlashni boshlash':status==='preparing'?'Tayyor bo‘ldi':'Mijozga topshirildi'
onMounted(()=>{load();timer=window.setInterval(()=>load(true),4000)})
onUnmounted(()=>timer&&window.clearInterval(timer))
</script>

<template>
  <div class="page-heading kitchen-heading"><div><span class="eyebrow">JONLI OSHXONA EKRANI</span><h1>Oshxona<span class="heading-dot">.</span></h1><p>Kassadan tushgan buyurtmalar har 4 soniyada avtomatik yangilanadi.</p></div><button class="button secondary" :disabled="loading" @click="load()"><RefreshCw :size="17" :class="{spin:loading}"/>Yangilash</button></div>
  <p v-if="error" class="alert error">{{ error }}</p>
  <div class="kitchen-summary"><div><span class="kitchen-dot queued"/><strong>{{ queued.length }}</strong><small>Yangi</small></div><div><span class="kitchen-dot preparing"/><strong>{{ preparing.length }}</strong><small>Tayyorlanmoqda</small></div><div><span class="kitchen-dot ready"/><strong>{{ ready.length }}</strong><small>Tayyor</small></div><span v-if="updated">Yangilandi: {{ updated.toLocaleTimeString('uz-UZ',{hour:'2-digit',minute:'2-digit',second:'2-digit'}) }}</span></div>
  <div class="kitchen-board">
    <section class="kitchen-column queued"><header><Clock3 :size="19"/><div><h2>Yangi buyurtmalar</h2><p>Tayyorlashni boshlash kerak</p></div><strong>{{ queued.length }}</strong></header><div class="kitchen-cards"><article v-for="order in queued" :key="order.id" class="kitchen-ticket is-new"><KitchenTicket :order="order"/><button class="button kitchen-action" :disabled="busy===order.id" @click="advance(order)"><ChefHat :size="17"/>{{ busy===order.id?'Saqlanmoqda…':actionLabel(order.preparation_status) }}</button></article><div v-if="!queued.length" class="kitchen-empty"><CheckCircle2/><span>Yangi buyurtma yo‘q</span></div></div></section>
    <section class="kitchen-column preparing"><header><ChefHat :size="19"/><div><h2>Tayyorlanmoqda</h2><p>Oshpaz ishlayotgan buyurtmalar</p></div><strong>{{ preparing.length }}</strong></header><div class="kitchen-cards"><article v-for="order in preparing" :key="order.id" class="kitchen-ticket"><KitchenTicket :order="order"/><button class="button kitchen-action" :disabled="busy===order.id" @click="advance(order)"><CheckCircle2 :size="17"/>{{ busy===order.id?'Saqlanmoqda…':actionLabel(order.preparation_status) }}</button></article><div v-if="!preparing.length" class="kitchen-empty"><ChefHat/><span>Jarayonda buyurtma yo‘q</span></div></div></section>
    <section class="kitchen-column ready"><header><CheckCircle2 :size="19"/><div><h2>Tayyor</h2><p>Mijozga berilishi kerak</p></div><strong>{{ ready.length }}</strong></header><div class="kitchen-cards"><article v-for="order in ready" :key="order.id" class="kitchen-ticket"><KitchenTicket :order="order"/><button class="button kitchen-action" :disabled="busy===order.id" @click="advance(order)"><Utensils :size="17"/>{{ busy===order.id?'Saqlanmoqda…':actionLabel(order.preparation_status) }}</button></article><div v-if="!ready.length" class="kitchen-empty"><Utensils/><span>Tayyor buyurtma yo‘q</span></div></div></section>
  </div>
</template>

// honim_frontend/src/pages/KitchenPage.tsx
import { useCallback, useEffect, useState } from 'react'
import { CheckCircle2, ChefHat, Clock3, RefreshCw, Utensils } from 'lucide-react'
import { api } from '../api'
import type { Order } from '../types'
import KitchenTicket from '../components/KitchenTicket'

const actionLabel = (status: string) =>
  status === 'queued' ? 'Tayyorlashni boshlash'
    : status === 'preparing' ? 'Tayyor bo‘ldi'
      : 'Mijozga topshirildi'

export default function KitchenPage() {
  const [orders, setOrders] = useState<Order[]>([])
  const [loading, setLoading] = useState(true)
  const [busy, setBusy] = useState<number>()
  const [error, setError] = useState('')
  const [updated, setUpdated] = useState<Date>()

  const load = useCallback(async (silent = false) => {
    if (!silent) setLoading(true)
    try {
      setOrders(await api<Order[]>('kitchen/orders/'))
      setUpdated(new Date())
      setError('')
    } catch (exception) {
      setError((exception as Error).message)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    load()
    const timer = window.setInterval(() => load(true), 4000)
    return () => window.clearInterval(timer)
  }, [load])

  async function advance(order: Order) {
    const next = order.preparation_status === 'queued' ? 'preparing'
      : order.preparation_status === 'preparing' ? 'ready'
        : 'served'
    setBusy(order.id)
    setError('')
    try {
      await api(`kitchen/orders/${order.id}/status/`, { method: 'POST', body: JSON.stringify({ status: next }) })
      await load(true)
    } catch (exception) {
      setError((exception as Error).message)
      await load(true)
    } finally {
      setBusy(undefined)
    }
  }

  const queued = orders.filter(order => order.preparation_status === 'queued')
  const preparing = orders.filter(order => order.preparation_status === 'preparing')
  const ready = orders.filter(order => order.preparation_status === 'ready')

  const columns = [
    { key: 'queued', rows: queued, icon: Clock3, actionIcon: ChefHat, title: 'Yangi buyurtmalar', caption: 'Tayyorlashni boshlash kerak', empty: 'Yangi buyurtma yo‘q', emptyIcon: CheckCircle2, isNew: true },
    { key: 'preparing', rows: preparing, icon: ChefHat, actionIcon: CheckCircle2, title: 'Tayyorlanmoqda', caption: 'Oshpaz ishlayotgan buyurtmalar', empty: 'Jarayonda buyurtma yo‘q', emptyIcon: ChefHat, isNew: false },
    { key: 'ready', rows: ready, icon: CheckCircle2, actionIcon: Utensils, title: 'Tayyor', caption: 'Mijozga berilishi kerak', empty: 'Tayyor buyurtma yo‘q', emptyIcon: Utensils, isNew: false },
  ]

  return (
    <>
      <div className="page-heading kitchen-heading">
        <div>
          <span className="eyebrow">JONLI OSHXONA EKRANI</span>
          <h1>Oshxona<span className="heading-dot">.</span></h1>
          <p>Kassadan tushgan buyurtmalar har 4 soniyada avtomatik yangilanadi.</p>
        </div>
        <button className="button secondary" disabled={loading} onClick={() => load()}>
          <RefreshCw size={17} className={loading ? 'spin' : undefined} />Yangilash
        </button>
      </div>
      {error && <p className="alert error">{error}</p>}
      <div className="kitchen-summary">
        <div><span className="kitchen-dot queued" /><strong>{queued.length}</strong><small>Yangi</small></div>
        <div><span className="kitchen-dot preparing" /><strong>{preparing.length}</strong><small>Tayyorlanmoqda</small></div>
        <div><span className="kitchen-dot ready" /><strong>{ready.length}</strong><small>Tayyor</small></div>
        {updated && (
          <span>
            Yangilandi: {updated.toLocaleTimeString('uz-UZ', { hour: '2-digit', minute: '2-digit', second: '2-digit' })}
          </span>
        )}
      </div>
      <div className="kitchen-board">
        {columns.map(column => {
          const Icon = column.icon
          const ActionIcon = column.actionIcon
          const EmptyIcon = column.emptyIcon
          return (
            <section key={column.key} className={`kitchen-column ${column.key}`}>
              <header>
                <Icon size={19} />
                <div><h2>{column.title}</h2><p>{column.caption}</p></div>
                <strong>{column.rows.length}</strong>
              </header>
              <div className="kitchen-cards">
                {column.rows.map(order => (
                  <article key={order.id} className={`kitchen-ticket${column.isNew ? ' is-new' : ''}`}>
                    <KitchenTicket order={order} />
                    <button className="button kitchen-action" disabled={busy === order.id} onClick={() => advance(order)}>
                      <ActionIcon size={17} />
                      {busy === order.id ? 'Saqlanmoqda…' : actionLabel(order.preparation_status)}
                    </button>
                  </article>
                ))}
                {!column.rows.length && (
                  <div className="kitchen-empty"><EmptyIcon /><span>{column.empty}</span></div>
                )}
              </div>
            </section>
          )
        })}
      </div>
    </>
  )
}
