// xonim_frontend/src/pages/PublicMenu.tsx
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowUpRight, Clock3, Leaf, MapPin, Search, Sparkles, UtensilsCrossed } from 'lucide-react'
import { api, money } from '../api'
import { useI18n } from '../i18n'
import type { Category, Dish } from '../types'
import DishArt from '../components/DishArt'

interface Menu {
  name: string
  categories: Category[]
  dishes: Dish[]
}

export default function PublicMenu() {
  const { t, tn } = useI18n()
  const [data, setData] = useState<Menu>()
  const [category, setCategory] = useState(0)
  const [search, setSearch] = useState('')
  const [error, setError] = useState('')

  const load = useCallback(async () => {
    setError('')
    try {
      setData(await api<Menu>('public/menu/xonim/'))
    } catch (exception) {
      setError((exception as Error).message)
    }
  }, [])

  useEffect(() => {
    load()
  }, [load])

  const visible = data?.dishes.filter(dish =>
    (!category || dish.category === category) &&
    dish.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()),
  ) || []
  const activeCategory = data?.categories.find(item => item.id === category)?.name || t('Barcha taomlar')

  return (
    <div className="public-menu">
      <header className="public-header">
        <Link to="/menu" className="brand">
          <span className="brand-mark">x<span>•</span></span>
          <span className="brand-text">xonim<span>{t('RESTORAN MENYUSI')}</span></span>
        </Link>
        <div className="public-header-meta">
          <span className="open-badge"><i /> {t('Bugun ochiq')}</span>
          <span className="public-language">{t('O‘zbekcha')}</span>
        </div>
      </header>
      <section className="menu-hero">
        <div className="hero-copy">
          <span className="eyebrow"><Sparkles size={13} /> {t('DID BILAN TAYYORLANGAN')}</span>
          <h1>{t('Ta’mlar')}<br /><em>{t('bir dasturxonda.')}</em></h1>
          <p>{t('Sevimli taomlaringizni tanlang.')}<br />{t('Buyurtmani ofitsiantga ayting.')}</p>
          <div className="hero-details">
            <span><UtensilsCrossed size={15} /> {tn('{count} ta taom', data?.dishes.length || 0)}</span>
            <span><Clock3 size={15} /> {t('Har kuni xizmatda')}</span>
          </div>
        </div>
        <div className="hero-ornament"><Leaf size={142} strokeWidth={0.8} /><span>XONIM<br />RESTAURANT</span></div>
      </section>
      <main className="public-content">
        <div className="menu-intro">
          <div><span className="eyebrow">{t('MENYU')}</span><h2>{activeCategory}</h2></div>
          <span className="menu-count">{tn('{count} ta tanlov', visible.length)}</span>
        </div>
        <div className="public-controls">
          <div className="tabs" aria-label={t('Taom kategoriyalari')}>
            <button className={!category ? 'selected' : undefined} onClick={() => setCategory(0)}>{t('Barchasi')}</button>
            {data?.categories.map(item => (
              <button
                key={item.id}
                className={category === item.id ? 'selected' : undefined}
                onClick={() => setCategory(item.id)}
              >
                {item.name}
              </button>
            ))}
          </div>
          <div className="search-field">
            <Search size={18} />
            <input
              value={search}
              onChange={event => setSearch(event.target.value)}
              placeholder={t('Taom qidiring')}
              aria-label={t('Taom qidirish')}
            />
          </div>
        </div>
        {error && (
          <p className="alert error">{error} <button className="text-link" onClick={load}>{t('Qayta urinish')}</button></p>
        )}
        {!data && !error && <div className="empty-state">{t('Menyu tayyorlanmoqda…')}</div>}
        <div className="dish-grid">
          {visible.map(dish => (
            <article key={dish.id} className="dish-card">
              <div className="dish-image-wrap">
                <DishArt name={dish.name} category={dish.category_name} image={dish.image} />
                {!dish.available && <span className="dish-state unavailable">{t('Hozir mavjud emas')}</span>}
              </div>
              <div className="dish-details">
                <span className="eyebrow">{dish.category_name}</span>
                <h3>{dish.name}</h3>
                {dish.description && <p>{dish.description}</p>}
                <footer>
                  <strong>{money(dish.price)} <small>{t('so‘m')}</small></strong>
                  <span>{dish.portion}</span>
                </footer>
              </div>
            </article>
          ))}
        </div>
        {data && !visible.length && <p className="empty-state">{t('Qidiruv bo‘yicha taom topilmadi.')}</p>}
      </main>
      <footer className="public-footer">
        <div className="footer-mark">x<span>•</span></div>
        <strong>xonim.</strong>
        <p><MapPin size={14} /> {t('Buyurtma berish uchun ofitsiantga murojaat qiling.')}</p>
        <Link to="/login">{t('Xodimlar uchun kirish')} <ArrowUpRight size={14} /></Link>
      </footer>
    </div>
  )
}

// honim_frontend/src/pages/PublicMenu.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Search, Leaf, ArrowUpRight, Clock3, MapPin, Sparkles, UtensilsCrossed } from '@lucide/vue'
import { api, money } from '../api'
import type { Category, Dish } from '../types'
import DishArt from '../components/DishArt.vue'

const data = ref<{ name: string; categories: Category[]; dishes: Dish[] }>()
const category = ref(0)
const search = ref('')
const error = ref('')
const visible = computed(() => data.value?.dishes.filter(d =>
  (!category.value || d.category === category.value) && d.name.toLocaleLowerCase().includes(search.value.toLocaleLowerCase()),
) || [])
const activeCategory = computed(() => data.value?.categories.find(item => item.id === category.value)?.name || 'Barcha taomlar')

async function load() {
  error.value = ''
  try { data.value = await api('public/menu/honim/') }
  catch (exception) { error.value = (exception as Error).message }
}

onMounted(load)
</script>

<template>
  <div class="public-menu">
    <header class="public-header">
      <RouterLink to="/menu" class="brand"><span class="brand-mark">h<span>•</span></span><span class="brand-text">honim<span>RESTORAN MENYUSI</span></span></RouterLink>
      <div class="public-header-meta"><span class="open-badge"><i /> Bugun ochiq</span><span class="public-language">O‘zbekcha</span></div>
    </header>
    <section class="menu-hero">
      <div class="hero-copy"><span class="eyebrow"><Sparkles :size="13" /> DID BILAN TAYYORLANGAN</span><h1>Ta’mlar<br><em>bir dasturxonda.</em></h1><p>Sevimli taomlaringizni tanlang.<br>Buyurtmani ofitsiantga ayting.</p><div class="hero-details"><span><UtensilsCrossed :size="15" /> {{ data?.dishes.length || 0 }} ta taom</span><span><Clock3 :size="15" /> Har kuni xizmatda</span></div></div>
      <div class="hero-ornament"><Leaf :size="142" :stroke-width="0.8" /><span>HONIM<br>RESTAURANT</span></div>
    </section>
    <main class="public-content">
      <div class="menu-intro"><div><span class="eyebrow">MENYU</span><h2>{{ activeCategory }}</h2></div><span class="menu-count">{{ visible.length }} ta tanlov</span></div>
      <div class="public-controls"><div class="tabs" aria-label="Taom kategoriyalari"><button :class="{ selected: !category }" @click="category = 0">Barchasi</button><button v-for="item in data?.categories" :key="item.id" :class="{ selected: category === item.id }" @click="category = item.id">{{ item.name }}</button></div><div class="search-field"><Search :size="18" /><input v-model="search" placeholder="Taom qidiring" aria-label="Taom qidirish"></div></div>
      <p v-if="error" class="alert error">{{ error }} <button class="text-link" @click="load">Qayta urinish</button></p>
      <div v-if="!data && !error" class="empty-state">Menyu tayyorlanmoqda…</div>
      <div class="dish-grid"><article v-for="dish in visible" :key="dish.id" class="dish-card"><div class="dish-image-wrap"><DishArt :name="dish.name" :category="dish.category_name" :image="dish.image" /><span v-if="!dish.available" class="dish-state unavailable">Hozir mavjud emas</span></div><div class="dish-details"><span class="eyebrow">{{ dish.category_name }}</span><h3>{{ dish.name }}</h3><p v-if="dish.description">{{ dish.description }}</p><footer><strong>{{ money(dish.price) }} <small>so‘m</small></strong><span>{{ dish.portion }}</span></footer></div></article></div>
      <p v-if="data && !visible.length" class="empty-state">Qidiruv bo‘yicha taom topilmadi.</p>
    </main>
    <footer class="public-footer"><div class="footer-mark">h<span>•</span></div><strong>honim.</strong><p><MapPin :size="14" /> Buyurtma berish uchun ofitsiantga murojaat qiling.</p><RouterLink to="/login">Xodimlar uchun kirish <ArrowUpRight :size="14" /></RouterLink></footer>
  </div>
</template>
