// honim_frontend/src/pages/StaffPage.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { Banknote, CalendarCheck, Download, Pencil, Plus, Search, ShieldCheck, UserRoundCog, Users } from '@lucide/vue'
import { api, download, money, today } from '../api'
import AppModal from '../components/AppModal.vue'

interface Staff {
  id: number; name: string; username: string; role: 'owner'|'admin'|'cashier'|'kitchen'; active: boolean
  phone: string; salary: string; hired_at: string|null; notes: string; last_login: string|null
  last_salary_period: string|null; last_salary_paid_on: string|null
}
interface SalaryPayment { id:number; period:string; amount:string; payment_method:'cash'|'card'; paid_on:string; note:string; actor_name:string }

const staff=ref<Staff[]>([]), payments=ref<SalaryPayment[]>([]), selected=ref<Staff>(), query=ref('')
const createOpen=ref(false), editOpen=ref(false), payOpen=ref(false), historyOpen=ref(false)
const busy=ref(false), error=ref(''), formError=ref('')
const currentMonth=today().slice(0,7)
const createForm=reactive({name:'',username:'',role:'admin',password:'',phone:'',salary:'',hired_at:today(),notes:''})
const editForm=reactive({name:'',role:'admin',phone:'',salary:'',hired_at:'',notes:'',active:true})
const payForm=reactive({period:currentMonth,amount:'',payment_method:'cash',paid_on:today(),note:''})
const filtered=computed(()=>staff.value.filter(item=>`${item.name} ${item.username} ${item.phone} ${item.role}`.toLocaleLowerCase().includes(query.value.toLocaleLowerCase())))
const employees=computed(()=>staff.value.filter(item=>item.role!=='owner'))
const activeCount=computed(()=>employees.value.filter(item=>item.active).length)
const monthlyPayroll=computed(()=>employees.value.filter(item=>item.active).reduce((sum,item)=>sum+Number(item.salary),0))
const paidThisMonth=computed(()=>employees.value.filter(item=>item.last_salary_period===currentMonth).length)

async function load(){try{staff.value=await api<Staff[]>('staff/')}catch(e){error.value=(e as Error).message}}
onMounted(load)
function startCreate(){Object.assign(createForm,{name:'',username:'',role:'admin',password:'',phone:'',salary:'',hired_at:today(),notes:''});formError.value='';createOpen.value=true}
async function createStaff(){busy.value=true;formError.value='';try{await api('staff/',{method:'POST',body:JSON.stringify({...createForm,salary:createForm.salary||'0',hired_at:createForm.hired_at||null})});createOpen.value=false;await load()}catch(e){formError.value=(e as Error).message}finally{busy.value=false}}
function startEdit(item:Staff){selected.value=item;Object.assign(editForm,{name:item.name,role:item.role,phone:item.phone,salary:item.salary,hired_at:item.hired_at||'',notes:item.notes,active:item.active});formError.value='';editOpen.value=true}
async function updateStaff(){if(!selected.value)return;busy.value=true;formError.value='';try{await api(`staff/${selected.value.id}/`,{method:'PATCH',body:JSON.stringify({...editForm,hired_at:editForm.hired_at||null})});editOpen.value=false;await load()}catch(e){formError.value=(e as Error).message}finally{busy.value=false}}
async function loadPayments(item:Staff){payments.value=await api<SalaryPayment[]>(`staff/${item.id}/salary-payments/`)}
async function startPay(item:Staff){selected.value=item;Object.assign(payForm,{period:currentMonth,amount:item.salary,payment_method:'cash',paid_on:today(),note:''});formError.value='';try{await loadPayments(item);payOpen.value=true}catch(e){error.value=(e as Error).message}}
async function paySalary(){if(!selected.value)return;busy.value=true;formError.value='';try{await api(`staff/${selected.value.id}/salary-payments/`,{method:'POST',body:JSON.stringify(payForm)});payOpen.value=false;await load()}catch(e){formError.value=(e as Error).message}finally{busy.value=false}}
async function showHistory(item:Staff){selected.value=item;error.value='';try{await loadPayments(item);historyOpen.value=true}catch(e){error.value=(e as Error).message}}
const roleName=(role:string)=>role==='owner'?'Superadmin':role==='admin'?'Admin':role==='kitchen'?'Oshxona':'Kassir'
async function exportPayroll(){try{await download('staff/salary-payments/export/','honim-umumiy-oyliklar.xlsx')}catch(e){error.value=(e as Error).message}}
</script>

<template>
  <div class="page-heading"><div><span class="eyebrow">JAMOA VA ISH HAQI</span><h1>Xodimlar<span class="heading-dot">.</span></h1><p>Hisoblar, lavozimlar va oylik to‘lovlari bir joyda.</p></div><div class="heading-actions"><button class="button secondary" @click="exportPayroll"><Download :size="17"/>Oyliklar Excel</button><button class="button primary" @click="startCreate"><Plus :size="18"/>Xodim yaratish</button></div></div>
  <p v-if="error" class="alert error">{{ error }}</p>
  <div class="staff-summary-grid">
    <article><Users/><span>Faol xodimlar</span><strong>{{ activeCount }}</strong><small>{{ employees.length }} ta xodim hisobidan</small></article>
    <article><Banknote/><span>Oylik ish haqi fondi</span><strong>{{ money(monthlyPayroll) }}</strong><small>so‘m / oy</small></article>
    <article><CalendarCheck/><span>{{ currentMonth }} da to‘langan</span><strong>{{ paidThisMonth }} / {{ activeCount }}</strong><small>har xodimga oyiga bir marta</small></article>
  </div>
  <section class="panel"><header class="panel-heading"><div><h2>Xodimlar ro‘yxati</h2><p>Rol, oylik va hisob holatini boshqaring</p></div><div class="search-field"><Search :size="17"/><input v-model="query" placeholder="Ism, login yoki telefon…" aria-label="Xodim qidirish"></div></header><div class="table-wrap"><table><thead><tr><th>XODIM</th><th>ROL</th><th>OYLIK</th><th>SO‘NGGI TO‘LOV</th><th>HOLAT</th><th>AMALLAR</th></tr></thead><tbody>
    <tr v-for="item in filtered" :key="item.id"><td><strong>{{ item.name }}</strong><small>@{{ item.username }}{{ item.phone?` · ${item.phone}`:'' }}</small></td><td><span class="pill subtle">{{ roleName(item.role) }}</span></td><td class="number">{{ item.role==='owner'?'—':`${money(item.salary)} so‘m` }}</td><td><span v-if="item.role==='owner'">—</span><template v-else-if="item.last_salary_period"><strong>{{ item.last_salary_period }}</strong><small>{{ item.last_salary_paid_on }}</small></template><span v-else>To‘lov yo‘q</span></td><td><span class="status" :class="item.active?'paid':'open'">{{ item.active?'Faol':'Bloklangan' }}</span></td><td><div v-if="item.role!=='owner'" class="staff-actions"><button class="table-action" title="Tahrirlash" @click="startEdit(item)"><Pencil :size="15"/></button><button class="table-action pay" @click="startPay(item)"><Banknote :size="15"/>Oylik</button><button class="text-link" @click="showHistory(item)">Tarix</button></div><small v-else>Bosh hisob</small></td></tr>
  </tbody></table><div v-if="!filtered.length" class="empty-state"><UserRoundCog :size="38" :stroke-width="1.3"/><h3>Xodim topilmadi</h3></div></div></section>
  <div class="inline-tip"><ShieldCheck :size="20"/><span>Oylik to‘lovi saqlanganda “Ish haqi” kategoriyasida xarajat yaratiladi va superadmin dashboardida darhol hisoblanadi.</span></div>

  <AppModal :open="createOpen" title="Yangi xodim hisobi" @close="!busy&&(createOpen=false)"><form @submit.prevent="createStaff">
    <div class="form-row"><label>Xodim ismi<input v-model="createForm.name" required maxlength="150" placeholder="Masalan, Azizbek"></label><label>Telefon<input v-model="createForm.phone" maxlength="30" placeholder="+998 90 123 45 67"></label></div>
    <div class="form-row"><label>Login<input v-model="createForm.username" required minlength="3" maxlength="150" pattern="[A-Za-z0-9_@.+-]+" autocomplete="off" placeholder="aziz_admin"></label><label>Rol<select v-model="createForm.role"><option value="admin">Admin</option><option value="cashier">Kassir</option><option value="kitchen">Oshxona</option></select></label></div>
    <div class="form-row"><label>Oylik, so‘m<input v-model="createForm.salary" type="number" min="0" step="1000" placeholder="3500000"></label><label>Ishga kirgan sana<input v-model="createForm.hired_at" type="date" :max="today()"></label></div>
    <label>Vaqtinchalik parol<input v-model="createForm.password" type="password" required minlength="12" maxlength="128" autocomplete="new-password" placeholder="Kamida 12 belgi"></label><label>Izoh<textarea v-model="createForm.notes" maxlength="300" rows="2" placeholder="Lavozim yoki qo‘shimcha ma’lumot"/></label>
    <p class="alert">Login va parolni xodimga xavfsiz yetkazing. Tizim parolni keyin qayta ko‘rsatmaydi.</p><p v-if="formError" class="alert error">{{ formError }}</p><button class="button primary full" :disabled="busy">{{ busy?'Yaratilmoqda…':'Hisobni yaratish' }}</button>
  </form></AppModal>

  <AppModal :open="editOpen" title="Xodim ma’lumotlari" @close="!busy&&(editOpen=false)"><form @submit.prevent="updateStaff">
    <div class="form-row"><label>Ism<input v-model="editForm.name" required maxlength="150"></label><label>Telefon<input v-model="editForm.phone" maxlength="30"></label></div><div class="form-row"><label>Rol<select v-model="editForm.role"><option value="admin">Admin</option><option value="cashier">Kassir</option><option value="kitchen">Oshxona</option></select></label><label>Oylik, so‘m<input v-model="editForm.salary" type="number" min="0" step="1000" required></label></div>
    <label>Ishga kirgan sana<input v-model="editForm.hired_at" type="date" :max="today()"></label><label>Izoh<textarea v-model="editForm.notes" maxlength="300" rows="2"/></label><label class="checkbox"><input v-model="editForm.active" type="checkbox">Hisob faol, tizimga kira oladi</label>
    <p v-if="formError" class="alert error">{{ formError }}</p><button class="button primary full" :disabled="busy">{{ busy?'Saqlanmoqda…':'O‘zgarishlarni saqlash' }}</button>
  </form></AppModal>

  <AppModal :open="payOpen" :title="`${selected?.name||''} · oylik to‘lovi`" @close="!busy&&(payOpen=false)"><form @submit.prevent="paySalary">
    <div class="salary-amount">{{ money(payForm.amount||0) }} <small>so‘m</small></div><div class="form-row"><label>Qaysi oy uchun?<input v-model="payForm.period" type="month" :max="currentMonth" required></label><label>To‘lov sanasi<input v-model="payForm.paid_on" type="date" :max="today()" required></label></div><div class="form-row"><label>Summa<input v-model="payForm.amount" type="number" min="1" step="1000" required></label><label>To‘lov usuli<select v-model="payForm.payment_method"><option value="cash">Naqd</option><option value="card">Karta</option></select></label></div><label>Izoh<textarea v-model="payForm.note" maxlength="250" rows="2" placeholder="Avans, bonus yoki boshqa izoh"/></label>
    <p class="alert">Bir xodimga bir oy uchun faqat bitta oylik to‘lovi yoziladi. To‘lov xarajatlarda ham aks etadi.</p><p v-if="formError" class="alert error">{{ formError }}</p><button class="button primary full" :disabled="busy">{{ busy?'Saqlanmoqda…':'Oylikni to‘langan deb belgilash' }}</button>
  </form></AppModal>

  <AppModal :open="historyOpen" :title="`${selected?.name||''} · to‘lovlar tarixi`" @close="historyOpen=false"><div class="salary-history"><div v-for="item in payments" :key="item.id"><span><strong>{{ item.period }}</strong><small>{{ item.paid_on }} · {{ item.payment_method==='cash'?'Naqd':'Karta' }} · {{ item.actor_name }}</small></span><strong>{{ money(item.amount) }} so‘m</strong><p v-if="item.note">{{ item.note }}</p></div><div v-if="!payments.length" class="empty-state compact"><Banknote :size="32"/><p>Hali oylik to‘lovi kiritilmagan.</p></div></div></AppModal>
</template>

// honim_frontend/src/pages/StaffPage.tsx
import { useCallback, useEffect, useState, type FormEvent } from 'react'
import {
  Banknote, CalendarCheck, Download, Pencil, Plus, Search, ShieldCheck, UserRoundCog, Users,
} from 'lucide-react'
import { Link } from 'react-router-dom'
import { api, download, money, today } from '../api'
import AppModal from '../components/AppModal'

interface Staff {
  id: number
  name: string
  username: string
  role: 'owner' | 'admin' | 'cashier' | 'kitchen'
  active: boolean
  phone: string
  salary: string
  hired_at: string | null
  notes: string
  last_login: string | null
  last_salary_period: string | null
  last_salary_paid_on: string | null
}

interface SalaryPayment {
  id: number
  period: string
  amount: string
  payment_method: 'cash' | 'card'
  paid_on: string
  note: string
  actor_name: string
}

interface CreateForm {
  name: string
  username: string
  role: string
  password: string
  phone: string
  salary: string
  hired_at: string
  notes: string
}

interface EditForm {
  name: string
  role: string
  phone: string
  salary: string
  hired_at: string
  notes: string
  active: boolean
}

interface PayForm {
  period: string
  amount: string
  payment_method: string
  paid_on: string
  note: string
}

const roleName = (role: string) =>
  role === 'owner' ? 'Superadmin' : role === 'admin' ? 'Admin' : role === 'kitchen' ? 'Oshxona' : 'Kassir'

export default function StaffPage() {
  const currentMonth = today().slice(0, 7)
  const [staff, setStaff] = useState<Staff[]>([])
  const [payments, setPayments] = useState<SalaryPayment[]>([])
  const [selected, setSelected] = useState<Staff>()
  const [query, setQuery] = useState('')
  const [createOpen, setCreateOpen] = useState(false)
  const [editOpen, setEditOpen] = useState(false)
  const [payOpen, setPayOpen] = useState(false)
  const [historyOpen, setHistoryOpen] = useState(false)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [formError, setFormError] = useState('')
  const [createForm, setCreateForm] = useState<CreateForm>({
    name: '', username: '', role: 'admin', password: '', phone: '', salary: '', hired_at: today(), notes: '',
  })
  const [editForm, setEditForm] = useState<EditForm>({
    name: '', role: 'admin', phone: '', salary: '', hired_at: '', notes: '', active: true,
  })
  const [payForm, setPayForm] = useState<PayForm>({
    period: currentMonth, amount: '', payment_method: 'cash', paid_on: today(), note: '',
  })

  const updateCreate = (patch: Partial<CreateForm>) => setCreateForm(previous => ({ ...previous, ...patch }))
  const updateEdit = (patch: Partial<EditForm>) => setEditForm(previous => ({ ...previous, ...patch }))
  const updatePay = (patch: Partial<PayForm>) => setPayForm(previous => ({ ...previous, ...patch }))

  const load = useCallback(async () => {
    try {
      setStaff(await api<Staff[]>('staff/'))
    } catch (exception) {
      setError((exception as Error).message)
    }
  }, [])

  useEffect(() => {
    load()
  }, [load])

  const filtered = staff.filter(item =>
    `${item.name} ${item.username} ${item.phone} ${item.role}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()),
  )
  const employees = staff.filter(item => item.role !== 'owner')
  const activeCount = employees.filter(item => item.active).length
  const monthlyPayroll = employees.filter(item => item.active).reduce((sum, item) => sum + Number(item.salary), 0)
  const paidThisMonth = employees.filter(item => item.last_salary_period === currentMonth).length

  function startCreate() {
    setCreateForm({
      name: '', username: '', role: 'admin', password: '', phone: '', salary: '', hired_at: today(), notes: '',
    })
    setFormError('')
    setCreateOpen(true)
  }

  async function createStaff(event: FormEvent) {
    event.preventDefault()
    setBusy(true)
    setFormError('')
    try {
      await api('staff/', {
        method: 'POST',
        body: JSON.stringify({
          ...createForm,
          salary: createForm.salary || '0',
          hired_at: createForm.hired_at || null,
        }),
      })
      setCreateOpen(false)
      await load()
    } catch (exception) {
      setFormError((exception as Error).message)
    } finally {
      setBusy(false)
    }
  }

  function startEdit(item: Staff) {
    setSelected(item)
    setEditForm({
      name: item.name,
      role: item.role,
      phone: item.phone,
      salary: item.salary,
      hired_at: item.hired_at || '',
      notes: item.notes,
      active: item.active,
    })
    setFormError('')
    setEditOpen(true)
  }

  async function updateStaff(event: FormEvent) {
    event.preventDefault()
    if (!selected) return
    setBusy(true)
    setFormError('')
    try {
      await api(`staff/${selected.id}/`, {
        method: 'PATCH',
        body: JSON.stringify({ ...editForm, hired_at: editForm.hired_at || null }),
      })
      setEditOpen(false)
      await load()
    } catch (exception) {
      setFormError((exception as Error).message)
    } finally {
      setBusy(false)
    }
  }

  async function loadPayments(item: Staff) {
    setPayments(await api<SalaryPayment[]>(`staff/${item.id}/salary-payments/`))
  }

  async function startPay(item: Staff) {
    setSelected(item)
    setPayForm({
      period: currentMonth, amount: item.salary, payment_method: 'cash', paid_on: today(), note: '',
    })
    setFormError('')
    try {
      await loadPayments(item)
      setPayOpen(true)
    } catch (exception) {
      setError((exception as Error).message)
    }
  }

  async function paySalary(event: FormEvent) {
    event.preventDefault()
    if (!selected) return
    setBusy(true)
    setFormError('')
    try {
      await api(`staff/${selected.id}/salary-payments/`, { method: 'POST', body: JSON.stringify(payForm) })
      setPayOpen(false)
      await load()
    } catch (exception) {
      setFormError((exception as Error).message)
    } finally {
      setBusy(false)
    }
  }

  async function showHistory(item: Staff) {
    setSelected(item)
    setError('')
    try {
      await loadPayments(item)
      setHistoryOpen(true)
    } catch (exception) {
      setError((exception as Error).message)
    }
  }

  async function exportPayroll() {
    try {
      await download('staff/salary-payments/export/', 'honim-umumiy-oyliklar.xlsx')
    } catch (exception) {
      setError((exception as Error).message)
    }
  }

  return (
    <>
      <div className="page-heading">
        <div>
          <span className="eyebrow">JAMOA VA ISH HAQI</span>
          <h1>Xodimlar<span className="heading-dot">.</span></h1>
          <p>Hisoblar, lavozimlar va oylik to‘lovlari bir joyda.</p>
        </div>
        <div className="heading-actions">
          <Link to="/payroll" className="button secondary"><Banknote size={17} />Oyliklar tahlili</Link>
          <button className="button secondary" onClick={exportPayroll}><Download size={17} />Oyliklar Excel</button>
          <button className="button primary" onClick={startCreate}><Plus size={18} />Xodim yaratish</button>
        </div>
      </div>
      {error && <p className="alert error">{error}</p>}
      <div className="staff-summary-grid">
        <article>
          <Users /><span>Faol xodimlar</span><strong>{activeCount}</strong>
          <small>{employees.length} ta xodim hisobidan</small>
        </article>
        <article>
          <Banknote /><span>Oylik ish haqi fondi</span><strong>{money(monthlyPayroll)}</strong><small>so‘m / oy</small>
        </article>
        <article>
          <CalendarCheck /><span>{currentMonth} da to‘langan</span>
          <strong>{paidThisMonth} / {activeCount}</strong><small>har xodimga oyiga bir marta</small>
        </article>
      </div>
      <section className="panel">
        <header className="panel-heading">
          <div><h2>Xodimlar ro‘yxati</h2><p>Rol, oylik va hisob holatini boshqaring</p></div>
          <div className="search-field">
            <Search size={17} />
            <input
              value={query}
              onChange={event => setQuery(event.target.value)}
              placeholder="Ism, login yoki telefon…"
              aria-label="Xodim qidirish"
            />
          </div>
        </header>
        <div className="table-wrap">
          <table>
            <thead>
              <tr><th>XODIM</th><th>ROL</th><th>OYLIK</th><th>SO‘NGGI TO‘LOV</th><th>HOLAT</th><th>AMALLAR</th></tr>
            </thead>
            <tbody>
              {filtered.map(item => (
                <tr key={item.id}>
                  <td>
                    <strong>{item.name}</strong>
                    <small>@{item.username}{item.phone ? ` · ${item.phone}` : ''}</small>
                  </td>
                  <td><span className="pill subtle">{roleName(item.role)}</span></td>
                  <td className="number">{item.role === 'owner' ? '—' : `${money(item.salary)} so‘m`}</td>
                  <td>
                    {item.role === 'owner' ? <span>—</span>
                      : item.last_salary_period ? (
                        <>
                          <strong>{item.last_salary_period}</strong>
                          <small>{item.last_salary_paid_on}</small>
                        </>
                      ) : <span>To‘lov yo‘q</span>}
                  </td>
                  <td>
                    <span className={`status ${item.active ? 'paid' : 'open'}`}>
                      {item.active ? 'Faol' : 'Bloklangan'}
                    </span>
                  </td>
                  <td>
                    {item.role !== 'owner' ? (
                      <div className="staff-actions">
                        <button className="table-action" title="Tahrirlash" onClick={() => startEdit(item)}>
                          <Pencil size={15} />
                        </button>
                        <button className="table-action pay" onClick={() => startPay(item)}>
                          <Banknote size={15} />Oylik
                        </button>
                        <button className="text-link" onClick={() => showHistory(item)}>Tarix</button>
                      </div>
                    ) : <small>Bosh hisob</small>}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          {!filtered.length && (
            <div className="empty-state"><UserRoundCog size={38} strokeWidth={1.3} /><h3>Xodim topilmadi</h3></div>
          )}
        </div>
      </section>
      <div className="inline-tip">
        <ShieldCheck size={20} />
        <span>
          Oylik to‘lovi saqlanganda “Ish haqi” kategoriyasida xarajat yaratiladi va superadmin dashboardida darhol hisoblanadi.
        </span>
      </div>

      <AppModal open={createOpen} title="Yangi xodim hisobi" onClose={() => { if (!busy) setCreateOpen(false) }}>
        <form onSubmit={createStaff}>
          <div className="form-row">
            <label>
              Xodim ismi
              <input
                value={createForm.name}
                onChange={event => updateCreate({ name: event.target.value })}
                required
                maxLength={150}
                placeholder="Masalan, Azizbek"
              />
            </label>
            <label>
              Telefon
              <input
                value={createForm.phone}
                onChange={event => updateCreate({ phone: event.target.value })}
                maxLength={30}
                placeholder="+998 90 123 45 67"
              />
            </label>
          </div>
          <div className="form-row">
            <label>
              Login
              <input
                value={createForm.username}
                onChange={event => updateCreate({ username: event.target.value })}
                required
                minLength={3}
                maxLength={150}
                pattern="[A-Za-z0-9_@.+-]+"
                autoComplete="off"
                placeholder="aziz_admin"
              />
            </label>
            <label>
              Rol
              <select value={createForm.role} onChange={event => updateCreate({ role: event.target.value })}>
                <option value="admin">Admin</option>
                <option value="cashier">Kassir</option>
                <option value="kitchen">Oshxona</option>
              </select>
            </label>
          </div>
          <div className="form-row">
            <label>
              Oylik, so‘m
              <input
                value={createForm.salary}
                onChange={event => updateCreate({ salary: event.target.value })}
                type="number"
                min="0"
                step="1000"
                placeholder="3500000"
              />
            </label>
            <label>
              Ishga kirgan sana
              <input
                value={createForm.hired_at}
                onChange={event => updateCreate({ hired_at: event.target.value })}
                type="date"
                max={today()}
              />
            </label>
          </div>
          <label>
            Vaqtinchalik parol
            <input
              value={createForm.password}
              onChange={event => updateCreate({ password: event.target.value })}
              type="password"
              required
              minLength={12}
              maxLength={128}
              autoComplete="new-password"
              placeholder="Kamida 12 belgi"
            />
          </label>
          <label>
            Izoh
            <textarea
              value={createForm.notes}
              onChange={event => updateCreate({ notes: event.target.value })}
              maxLength={300}
              rows={2}
              placeholder="Lavozim yoki qo‘shimcha ma’lumot"
            />
          </label>
          <p className="alert">Login va parolni xodimga xavfsiz yetkazing. Tizim parolni keyin qayta ko‘rsatmaydi.</p>
          {formError && <p className="alert error">{formError}</p>}
          <button className="button primary full" disabled={busy}>
            {busy ? 'Yaratilmoqda…' : 'Hisobni yaratish'}
          </button>
        </form>
      </AppModal>

      <AppModal open={editOpen} title="Xodim ma’lumotlari" onClose={() => { if (!busy) setEditOpen(false) }}>
        <form onSubmit={updateStaff}>
          <div className="form-row">
            <label>
              Ism
              <input value={editForm.name} onChange={event => updateEdit({ name: event.target.value })} required maxLength={150} />
            </label>
            <label>
              Telefon
              <input value={editForm.phone} onChange={event => updateEdit({ phone: event.target.value })} maxLength={30} />
            </label>
          </div>
          <div className="form-row">
            <label>
              Rol
              <select value={editForm.role} onChange={event => updateEdit({ role: event.target.value })}>
                <option value="admin">Admin</option>
                <option value="cashier">Kassir</option>
                <option value="kitchen">Oshxona</option>
              </select>
            </label>
            <label>
              Oylik, so‘m
              <input
                value={editForm.salary}
                onChange={event => updateEdit({ salary: event.target.value })}
                type="number"
                min="0"
                step="1000"
                required
              />
            </label>
          </div>
          <label>
            Ishga kirgan sana
            <input
              value={editForm.hired_at}
              onChange={event => updateEdit({ hired_at: event.target.value })}
              type="date"
              max={today()}
            />
          </label>
          <label>
            Izoh
            <textarea
              value={editForm.notes}
              onChange={event => updateEdit({ notes: event.target.value })}
              maxLength={300}
              rows={2}
            />
          </label>
          <label className="checkbox">
            <input type="checkbox" checked={editForm.active} onChange={event => updateEdit({ active: event.target.checked })} />
            Hisob faol, tizimga kira oladi
          </label>
          {formError && <p className="alert error">{formError}</p>}
          <button className="button primary full" disabled={busy}>
            {busy ? 'Saqlanmoqda…' : 'O‘zgarishlarni saqlash'}
          </button>
        </form>
      </AppModal>

      <AppModal
        open={payOpen}
        title={`${selected?.name || ''} · oylik to‘lovi`}
        onClose={() => { if (!busy) setPayOpen(false) }}
      >
        <form onSubmit={paySalary}>
          <div className="salary-amount">{money(payForm.amount || 0)} <small>so‘m</small></div>
          <div className="form-row">
            <label>
              Qaysi oy uchun?
              <input
                value={payForm.period}
                onChange={event => updatePay({ period: event.target.value })}
                type="month"
                max={currentMonth}
                required
              />
            </label>
            <label>
              To‘lov sanasi
              <input
                value={payForm.paid_on}
                onChange={event => updatePay({ paid_on: event.target.value })}
                type="date"
                max={today()}
                required
              />
            </label>
          </div>
          <div className="form-row">
            <label>
              Summa
              <input
                value={payForm.amount}
                onChange={event => updatePay({ amount: event.target.value })}
                type="number"
                min="1"
                step="1000"
                required
              />
            </label>
            <label>
              To‘lov usuli
              <select value={payForm.payment_method} onChange={event => updatePay({ payment_method: event.target.value })}>
                <option value="cash">Naqd</option>
                <option value="card">Karta</option>
              </select>
            </label>
          </div>
          <label>
            Izoh
            <textarea
              value={payForm.note}
              onChange={event => updatePay({ note: event.target.value })}
              maxLength={250}
              rows={2}
              placeholder="Avans, bonus yoki boshqa izoh"
            />
          </label>
          <p className="alert">
            Bir xodimga bir oy uchun faqat bitta oylik to‘lovi yoziladi. To‘lov xarajatlarda ham aks etadi.
          </p>
          {formError && <p className="alert error">{formError}</p>}
          <button className="button primary full" disabled={busy}>
            {busy ? 'Saqlanmoqda…' : 'Oylikni to‘langan deb belgilash'}
          </button>
        </form>
      </AppModal>

      <AppModal
        open={historyOpen}
        title={`${selected?.name || ''} · to‘lovlar tarixi`}
        onClose={() => setHistoryOpen(false)}
      >
        <div className="salary-history">
          {payments.map(item => (
            <div key={item.id}>
              <span>
                <strong>{item.period}</strong>
                <small>{item.paid_on} · {item.payment_method === 'cash' ? 'Naqd' : 'Karta'} · {item.actor_name}</small>
              </span>
              <strong>{money(item.amount)} so‘m</strong>
              {item.note && <p>{item.note}</p>}
            </div>
          ))}
          {!payments.length && (
            <div className="empty-state compact"><Banknote size={32} /><p>Hali oylik to‘lovi kiritilmagan.</p></div>
          )}
        </div>
      </AppModal>
    </>
  )
}
